[package]
name = "Petrichor"
version = "0.1.0"
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.12.0"
cpal="0.13.4"
bytemuck= { version = "1.7.2", features = ["derive"] }
cgmath="0.18.0"
winit = "0.26.0"
pollster = "0.2"
log="0.4.14"
env_logger = "0.9"
lazy_static="1.4.0"
parking_lot ="0.11.2"
anyhow="1.0.51"
image ="0.23.14"