
[package]
name = "Petrichor"
version = "0.1.0"
edition = "2021"
resolver = "2"

[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = "z"  # Optimize for size.
lto = true

[features]
include_auto=[]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.12.0"
cpal="0.13.4"
bytemuck= { version = "1.7.2", features = ["derive"] }

winit = "0.26.0"
winit_input_helper="0.11.0"
pollster = "0.2"
log="0.4.14"
env_logger = "0.9"
lazy_static="1.4.0"
parking_lot ="0.11.2"
anyhow="1.0.51"
image ="0.24.3"
imageproc="0.23.0"
once_cell="1.9.0"
gltf="0.16.0"
itertools="0.10.3"
serde="1.0.133"
mlua={version= "^0.7.1", features=["lua54","vendored"]}
rand="0.8.4"
glam="0.20.2"
nalgebra="0.30.1"
uuid = {version="0.8.2",features = ["serde", "v4"]}
zip="0.6.0"
spin_sleep = "1.1.1"
clipboard = "0.5.0"
rustc-hash = "1.1.0"
ron="0.7.0"
gilrs ="0.9.0"
serde_json ="1.0.81"
tokio = { version = "1.20.1", features = ["full"] }
tokio-util= { version = "0.7.3", features = ["codec"] } 
bytes="1.2.1"
futures="0.3.21"

# [dependencies.tracy]
# package = "tracy_full"
# version = "1.1.2"
# default-features = false
# features = ["enable","system-tracing", "context-switch-tracing", "sampling", "code-transfer", "broadcast","wgpu"]