[package]
name = "Petrichor"
version = "0.1.0"
edition = "2018"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.11"
winit = "0.25"
pollster = "0.2"
env_logger = "0.9"