
[package]
name = "Petrichor"
version = "0.1.0"
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.12.0"
cpal="0.13.4"
bytemuck= { version = "1.7.2", features = ["derive"] }

winit = "0.26.0"
winit_input_helper="0.11.0"
pollster = "0.2"
log="0.4.14"
env_logger = "0.9"
lazy_static="1.4.0"
parking_lot ="0.11.2"
anyhow="1.0.51"
image ="0.23.14"
once_cell="1.9.0"
gltf="0.16.0"
itertools="0.10.3"
serde="1.0.133"
mlua={version= "^0.7.1", features=["lua54","vendored"]}
rand="0.8.4"
glam="0.20.2"